# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNZenDeskSupport' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'ZendeskSDK'

  # Pods for RNZenDeskSupport

end
